import type { Formatter } from '@saykit/config';
import PO from 'pofile';

function createFormatter(): Formatter {
  return {
    extension: '.po',

    async parse(content, context) {
      const po = PO.parse(content);

      if (!po.headers['X-Generator']?.startsWith('saykit'))
        throw new Error('PO file was not generated by saykit');
      if (po.headers.Language !== context.locale)
        throw new Error('PO file locale does not match the expected locale');

      return po.items.map((item) => {
        const id = item.extractedComments.find((c) => c.startsWith('id:'))?.slice(3);
        const comments = item.extractedComments //
          .filter((c) => !c.startsWith('id:'))
          .map((c) => c.trim());

        return {
          id,
          context: item.msgctxt,
          message: item.msgid,
          translation: item.msgstr[0],
          comments,
          references: item.references,
        };
      });
    },

    async stringify(messages, context) {
      const po = new PO();

      po.headers['Content-Type'] = 'text/plain; charset=UTF-8';
      po.headers['Content-Transfer-Encoding'] = '8bit';
      po.headers.Language = context.locale;
      po.headers['X-Generator'] = 'saykit';

      for (const message of messages.sort((a, b) => a.message.localeCompare(b.message))) {
        const item = new PO.Item();

        item.msgid = message.message;
        if (message.context) item.msgctxt = message.context;
        item.msgstr = [message.translation ?? ''];

        const comments = [];
        if (message.id) comments.push(`id:${message.id}`);
        if (message.comments.length) comments.push(...message.comments);
        item.extractedComments = comments;

        item.references = message.references;
        po.items.push(item);
      }

      return po.toString();
    },
  };
}

export default createFormatter;
